# -*- coding: utf-8 -*-
"""Exercise1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1A2nzMJ7Jyl4msw0AjBpYddoyGLcPUKwW
"""

# Write a function that takes two lists representing ses (with no duplicates) which returns a list of the intersection.

# (use only loops and sequence indexing with no method calls except append).

# Use a nested loop in your implementation. Teset on the list A = [2, 4, 5,6] and B = [4, 6, 7, 8].


def intersection(A,B):
    match = []
    for x in A:
        for y in B:
            if x == y:
                match.append(x)
        return match

intersection(A=[2, 4, 5, 6], B = [4,6,7,8])