# -*- coding: utf-8 -*-
"""gcm.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1A2nzMJ7Jyl4msw0AjBpYddoyGLcPUKwW
"""

def gcd(a, b):
  print(str(a)+" "+str(b)+"\n")
  if b == 0:
    return a
  else:
    return gcd(b, (a % b))

gcd(1220, 516)